// Tool-specific canvas cards. Each tool kind gets its own renderer that
// presents the output as the user wants to *see* it (a wiki abstract, a
// candlestick chart, a link preview) rather than raw JSON. When we can't parse
// the truncated output (or the tool isn't specifically handled yet), a
// generic fallback card shows the bare facts.

import { For, Show, createEffect, createMemo, onCleanup, onMount } from "solid-js";
import { CandlestickSeries, createChart, type IChartApi, type ISeriesApi } from "lightweight-charts";
import { SafeMarkdown } from "./SafeMarkdown";

export interface ToolCallView {
  call_id: string;
  status: "in_progress" | "completed" | "error" | string;
  name: string;
  arguments?: string;
  output_preview?: string;
  output_bytes?: number;
}

export interface SearchCallView {
  status: string;
  action: string;
  detail: string;
}

/** Match LiveChat's `searchKey` exactly so chat clicks resolve to the same
 *  data-call-id on the canvas tile. Keep these in sync. */
function searchKey(s: SearchCallView): string {
  return `search:${s.action}:${(s.detail || "").slice(0, 120)}`;
}

export interface NarrationStep {
  turn: number;
  text: string;
}

interface ArtifactCallbacks {
  onOpenDoc?: (id: string, title: string) => void;
}

export function ArtifactPanel(props: {
  searches: SearchCallView[];
  tools: ToolCallView[];
  narrations?: NarrationStep[];
  callbacks?: ArtifactCallbacks;
}) {
  return (
    <div class="lk-artifact-grid" style={{
      position: "absolute",
      top: "56px",
      left: "24px",
      right: "24px",
      bottom: "20px",
      "padding-top": "4px",
      overflow: "auto",
      display: "grid",
      "grid-template-columns": "repeat(auto-fill, minmax(280px, 1fr))",
      "grid-auto-rows": "min-content",
      "grid-auto-flow": "dense",
      gap: "12px",
    }}>
      {/* Spacer reserves the brain widget's 240x240 footprint in the top-right
          corner so cards don't slide under it. `grid-column: -2 / -1` targets
          the last implicit column generated by auto-fill. */}
      <div style={{
        "grid-column": "-2 / -1",
        "grid-row": "1 / span 2",
        height: "252px",
        visibility: "hidden",
      }} />
      <For each={props.narrations ?? []}>{(n) => <NarrationCard step={n} />}</For>
      <For each={props.searches}>{(s) => <SearchArtifact search={s} />}</For>
      <For each={props.tools}>{(t) => (
        <ToolArtifact tool={t} callbacks={props.callbacks} />
      )}</For>
    </div>
  );
}

function NarrationCard(props: { step: NarrationStep }) {
  return (
    <div style={{
      "grid-column": "span 1",
      "border-left": "3px solid var(--clay)",
      padding: "8px 14px",
      background: "rgba(217, 119, 87, 0.04)",
      "border-radius": "0 6px 6px 0",
      "font-size": "12.5px",
      "line-height": 1.55,
      color: "var(--ink-1)",
    }}>
      <div style={{
        "font-family": "var(--font-mono)",
        "font-size": "10px",
        "text-transform": "uppercase",
        "letter-spacing": "0.06em",
        color: "var(--clay-soft)",
        "margin-bottom": "4px",
      }}>
        thinking · turn {props.step.turn + 1}
      </div>
      <SafeMarkdown source={props.step.text} />
    </div>
  );
}

function StatusDot(props: { status: string }) {
  const color = () =>
    props.status === "completed" ? "#9eb78f" :
    props.status === "error" ? "#d97070" : "#d9a76c";
  return (
    <span style={{
      width: "6px",
      height: "6px",
      "border-radius": "50%",
      background: color(),
      display: "inline-block",
      "margin-right": "8px",
      "flex-shrink": 0,
    }} />
  );
}

function CardShell(props: {
  status: string;
  badge: string;
  detail?: string;
  children: any;
  onClick?: () => void;
  /** Marks the card so chat-side click handlers can scrollIntoView. */
  callId?: string;
  /** How many grid columns this card spans (default 1). */
  span?: number;
}) {
  return (
    <div
      onClick={props.onClick}
      data-call-id={props.callId}
      style={{
        "grid-column": `span ${props.span ?? 1}`,
        background: "var(--bg-1)",
        border: "1px solid var(--bg-2)",
        "border-radius": "8px",
        padding: "12px 14px",
        cursor: props.onClick ? "pointer" : "default",
        transition: "border-color 120ms, box-shadow 200ms",
      }}
    >
      <div style={{
        display: "flex",
        "align-items": "center",
        gap: "0",
        "margin-bottom": "8px",
        "font-family": "var(--font-mono)",
        "font-size": "10.5px",
        color: "var(--ink-3)",
        "text-transform": "uppercase",
        "letter-spacing": "0.04em",
      }}>
        <StatusDot status={props.status} />
        <span style={{ color: "var(--ink-2)", "font-weight": 600 }}>{props.badge}</span>
        <Show when={props.detail}>
          <span style={{
            "margin-left": "10px",
            "text-transform": "none",
            "letter-spacing": "0",
            overflow: "hidden",
            "text-overflow": "ellipsis",
            "white-space": "nowrap",
          }}>
            {props.detail}
          </span>
        </Show>
      </div>
      {props.children}
    </div>
  );
}

function SearchArtifact(props: { search: SearchCallView }) {
  const verb = () => props.search.status === "completed"
    ? props.search.action === "open_page" ? "Opened"
    : props.search.action === "find_in_page" ? "Found in page"
    : "Searched"
    : props.search.action === "open_page" ? "Opening"
    : "Searching";
  let host = props.search.detail;
  let isUrl = false;
  try {
    const u = new URL(props.search.detail);
    host = u.hostname.replace(/^www\./, "");
    isUrl = true;
  } catch {/* leave as is */}

  const onClick = () => {
    if (isUrl) window.open(props.search.detail, "_blank", "noopener,noreferrer");
  };

  return (
    <div
      data-call-id={searchKey(props.search)}
      onClick={isUrl ? onClick : undefined}
      style={{
        "grid-column": "span 1",
        background: "var(--bg-1)",
        border: "1px solid var(--bg-2)",
        "border-radius": "8px",
        padding: "12px 14px",
        cursor: isUrl ? "pointer" : "default",
        transition: "border-color 120ms, box-shadow 200ms",
        display: "flex",
        "flex-direction": "column",
        gap: "6px",
      }}
    >
      <div style={{
        display: "flex",
        "align-items": "center",
        "font-family": "var(--font-mono)",
        "font-size": "10.5px",
        color: "var(--ink-3)",
        "text-transform": "uppercase",
        "letter-spacing": "0.04em",
      }}>
        <StatusDot status={props.search.status} />
        <span style={{ color: "var(--ink-2)", "font-weight": 600 }}>web · search</span>
        <span style={{ "margin-left": "10px", "text-transform": "none", "letter-spacing": "0" }}>
          {verb()}
        </span>
      </div>
      <div style={{
        "font-size": "13px",
        color: isUrl ? "var(--ink-1)" : "var(--ink-2)",
        "word-break": "break-word",
        "line-height": 1.4,
      }}>
        {isUrl ? host : (props.search.detail || "—")}
      </div>
      <Show when={isUrl}>
        <div style={{
          "font-family": "var(--font-mono)",
          "font-size": "10.5px",
          color: "var(--ink-3)",
          "white-space": "nowrap",
          overflow: "hidden",
          "text-overflow": "ellipsis",
        }}>{props.search.detail}</div>
      </Show>
    </div>
  );
}

function ToolArtifact(props: { tool: ToolCallView; callbacks?: ArtifactCallbacks }) {
  switch (props.tool.name) {
    case "corpus_search": return <CorpusSearchCard {...props} />;
    case "web_fetch":     return <WebFetchCard {...props} />;
    case "tradingview_quote": return <TradingViewCard {...props} />;
    case "tushare_quote": return <TushareCard {...props} />;
    case "sec_filing_fetch": return <SecFilingCard {...props} />;
    default:              return <GenericToolCard {...props} />;
  }
}

function safeParseJson(s: string | undefined): unknown {
  if (!s) return null;
  try { return JSON.parse(s); }
  catch {
    // Truncated JSON — try shaving the tail until we get a parseable prefix.
    for (let i = s.length - 1; i > 32; i--) {
      const tail = s.slice(0, i);
      try { return JSON.parse(tail); } catch {/* keep shaving */}
    }
    return null;
  }
}

/** Pull complete `{...}` objects out of a JSON array literal whose tail is
 *  truncated. Used to salvage partial corpus_search / sec_filing_fetch outputs
 *  where the preview cap cuts inside the last entry. */
function extractObjectsAfter(s: string, marker: string): unknown[] {
  const startIdx = s.indexOf(marker);
  if (startIdx < 0) return [];
  let i = startIdx + marker.length;
  // Skip to the `[`
  while (i < s.length && s[i] !== "[") i++;
  if (s[i] !== "[") return [];
  i++;
  const out: unknown[] = [];
  while (i < s.length) {
    while (i < s.length && /[\s,]/.test(s[i])) i++;
    if (s[i] !== "{") break;
    const start = i;
    let depth = 0;
    let inStr = false;
    let esc = false;
    let end = -1;
    for (; i < s.length; i++) {
      const c = s[i];
      if (esc) { esc = false; continue; }
      if (c === "\\") { esc = true; continue; }
      if (c === '"') { inStr = !inStr; continue; }
      if (inStr) continue;
      if (c === "{") depth++;
      else if (c === "}") {
        depth--;
        if (depth === 0) { end = i; i++; break; }
      }
    }
    if (end < 0) break;
    try { out.push(JSON.parse(s.slice(start, end + 1))); }
    catch {/* skip malformed entry */}
  }
  return out;
}

function parseArgs(t: ToolCallView): Record<string, unknown> {
  if (!t.arguments) return {};
  try { return JSON.parse(t.arguments); }
  catch { return {}; }
}

/* ---------- corpus_search ---------- */

interface CorpusHit {
  id: string;
  title: string;
  tier: string;
  layer: string;
  tags?: string[];
  score?: number;
  snippet?: string;
}

function CorpusSearchCard(props: { tool: ToolCallView; callbacks?: ArtifactCallbacks }) {
  const args = parseArgs(props.tool);
  const query = String(args.query ?? "");
  const preview = props.tool.output_preview ?? "";
  const parsed = safeParseJson(preview) as
    | { hits?: CorpusHit[]; total_corpus_docs?: number } | null;
  // Fall back to brace-balanced extraction when the preview was truncated
  // mid-record (preview cap < full output).
  const hits: CorpusHit[] = parsed?.hits
    ?? (extractObjectsAfter(preview, "\"hits\"") as CorpusHit[]);
  return (
    <CardShell
      status={props.tool.status}
      badge="corpus"
      detail={query ? `"${query}"` : undefined}
      callId={props.tool.call_id}
    >
      <Show
        when={hits.length > 0}
        fallback={
          <div style={{ color: "var(--ink-3)", "font-size": "11.5px" }}>
            <Show when={props.tool.status === "in_progress"} fallback="No hits.">
              Searching the corpus…
            </Show>
          </div>
        }
      >
        <div style={{ display: "flex", "flex-direction": "column", gap: "6px" }}>
          <For each={hits.slice(0, 5)}>{(h) => (
            <CorpusHitTile hit={h} onOpen={() =>
              props.callbacks?.onOpenDoc?.(h.id, h.title || h.id)
            } />
          )}</For>
        </div>
      </Show>
    </CardShell>
  );
}

function CorpusHitTile(props: { hit: CorpusHit; onOpen: () => void }) {
  const tierLabel = () => `${props.hit.tier}·${props.hit.layer}`;
  return (
    <div
      onClick={(e) => { e.stopPropagation(); props.onOpen(); }}
      title="Click to open the full wiki page"
      style={{
        cursor: "pointer",
        padding: "5px 8px",
        background: "rgba(255, 255, 255, 0.025)",
        border: "1px solid var(--line-1)",
        "border-radius": "4px",
        display: "flex",
        "align-items": "center",
        gap: "8px",
        "min-height": "24px",
      }}
    >
      <span style={{
        "font-size": "12px",
        color: "var(--ink-0)",
        flex: 1,
        overflow: "hidden",
        "text-overflow": "ellipsis",
        "white-space": "nowrap",
      }}>{props.hit.title}</span>
      <span style={{
        "font-family": "var(--font-mono)",
        "font-size": "9.5px",
        color: "var(--ink-3)",
        "flex-shrink": 0,
      }}>{tierLabel()}</span>
    </div>
  );
}

/* ---------- web_fetch · link preview ---------- */

export interface LinkMeta {
  title: string;
  description: string;
  thumbnail?: string;
}

/** Pull page title (first `# heading`), short description, and thumbnail
 *  (first markdown image) out of the truncated readability output. */
export function extractLinkMeta(md: string): LinkMeta {
  // The fetched markdown is preceded by "# Source: <url>\n_(extraction: ...)_\n\n"
  // — strip both lines first.
  const body = md
    .replace(/^# Source:[^\n]*\n/, "")
    .replace(/^_\(extraction:[^\n]*\)_\n\n/m, "")
    .trim();

  const titleMatch = body.match(/^#{1,3}\s+(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : "";

  // Description: text after the title, first non-empty paragraph, plain-text-ified.
  const afterTitle = title
    ? body.slice((titleMatch?.index ?? 0) + (titleMatch?.[0].length ?? 0)).trim()
    : body;
  // Skip image-only paragraphs and metadata lines (italic single-line).
  const paragraphs = afterTitle.split(/\n\n+/);
  let desc = "";
  for (const p of paragraphs) {
    const stripped = p
      .replace(/!\[[^\]]*\]\([^)]+\)/g, "")
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      .replace(/[*_`>#]+/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (stripped.length >= 20) {
      desc = stripped;
      break;
    }
  }
  if (desc.length > 160) desc = desc.slice(0, 157).trimEnd() + "…";

  const imgMatch = body.match(/!\[[^\]]*\]\((https?:\/\/[^)\s]+)\)/);
  const thumbnail = imgMatch?.[1];

  return { title, description: desc, thumbnail };
}

function WebFetchCard(props: { tool: ToolCallView }) {
  const args = parseArgs(props.tool);
  const url = String(args.url ?? "");
  let host = url;
  try { host = new URL(url).hostname.replace(/^www\./, ""); } catch {/* leave */}
  const favicon = host
    ? `https://www.google.com/s2/favicons?domain=${encodeURIComponent(host)}&sz=64`
    : "";

  const meta = createMemo(() => extractLinkMeta(props.tool.output_preview ?? ""));

  return (
    <div
      onClick={url ? () => window.open(url, "_blank", "noopener,noreferrer") : undefined}
      data-call-id={props.tool.call_id}
      style={{
        "grid-column": "span 1",
        background: "var(--bg-1)",
        border: "1px solid var(--bg-2)",
        "border-radius": "8px",
        cursor: url ? "pointer" : "default",
        transition: "border-color 120ms, box-shadow 200ms",
        overflow: "hidden",
        display: "flex",
        "flex-direction": "column",
      }}
    >
      <Show when={meta().thumbnail}>
        <div style={{
          width: "100%",
          height: "120px",
          "background-image": `url(${meta().thumbnail})`,
          "background-size": "cover",
          "background-position": "center",
          "background-color": "var(--bg-2)",
          "border-bottom": "1px solid var(--bg-2)",
        }} />
      </Show>
      <div style={{ padding: "12px 14px", display: "flex", "flex-direction": "column", gap: "6px" }}>
        <div style={{
          display: "flex",
          "align-items": "center",
          gap: "6px",
          "font-family": "var(--font-mono)",
          "font-size": "10.5px",
          color: "var(--ink-3)",
          "text-transform": "uppercase",
          "letter-spacing": "0.04em",
        }}>
          <StatusDot status={props.tool.status} />
          <Show when={favicon}>
            <img src={favicon} width="14" height="14" alt="" style={{
              "border-radius": "3px",
              "flex-shrink": 0,
            }} />
          </Show>
          <span style={{
            "text-transform": "none",
            "letter-spacing": "0",
            overflow: "hidden",
            "text-overflow": "ellipsis",
            "white-space": "nowrap",
          }}>{host}</span>
        </div>
        <Show
          when={meta().title || meta().description}
          fallback={
            <div style={{ color: "var(--ink-3)", "font-size": "12px" }}>
              <Show when={props.tool.status === "in_progress"} fallback="No content.">
                Fetching…
              </Show>
            </div>
          }
        >
          <Show when={meta().title}>
            <div style={{
              "font-size": "13.5px",
              "font-weight": 600,
              color: "var(--ink-0)",
              "line-height": 1.35,
              display: "-webkit-box",
              "-webkit-line-clamp": "2",
              "-webkit-box-orient": "vertical",
              overflow: "hidden",
            }}>{meta().title}</div>
          </Show>
          <Show when={meta().description}>
            <div style={{
              "font-size": "12px",
              color: "var(--ink-2)",
              "line-height": 1.5,
              display: "-webkit-box",
              "-webkit-line-clamp": "3",
              "-webkit-box-orient": "vertical",
              overflow: "hidden",
            }}>{meta().description}</div>
          </Show>
        </Show>
      </div>
    </div>
  );
}

/* ---------- tradingview_quote · multi-ticker quote chips ---------- */

interface TVQuoteRow {
  symbol: string;
  name: string;
  close: string;
  pct: string;
  abs: string;
  vol: string;
  cap: string;
  tech: string;
}

/** Parse the markdown table tradingview emits — each row is one ticker
 *  snapshot. Returns the rows in DOM order. */
function parseTradingViewTable(md: string): TVQuoteRow[] {
  const out: TVQuoteRow[] = [];
  const lines = md.split("\n");
  for (const line of lines) {
    if (!line.startsWith("|") || line.startsWith("|---") || line.includes("symbol")) continue;
    const cells = line.split("|").map((c) => c.trim()).filter((_, i, arr) => i > 0 && i < arr.length - 1);
    if (cells.length < 8) continue;
    const [symbol, name, close, pct, abs, vol, cap, tech] = cells;
    if (!symbol || symbol === "—") continue;
    out.push({ symbol, name, close, pct, abs, vol, cap, tech });
  }
  return out;
}

function TradingViewCard(props: { tool: ToolCallView }) {
  const args = parseArgs(props.tool);
  const tickers = Array.isArray(args.tickers) ? (args.tickers as string[]) : [];
  const rows = createMemo(() => parseTradingViewTable(props.tool.output_preview ?? ""));
  // Wider cards for >2 tickers so chips don't crush.
  const span = () => (tickers.length > 2 ? 2 : 1);

  return (
    <CardShell
      status={props.tool.status}
      badge="market · tradingview"
      detail={tickers.join(", ")}
      callId={props.tool.call_id}
      span={span()}
    >
      <Show
        when={rows().length > 0}
        fallback={
          <div style={{ color: "var(--ink-3)", "font-size": "11.5px" }}>
            <Show when={props.tool.status === "in_progress"} fallback="No quotes.">
              Fetching quotes…
            </Show>
          </div>
        }
      >
        <div style={{ display: "flex", "flex-direction": "column", gap: "6px" }}>
          <For each={rows()}>{(r) => <QuoteChip row={r} />}</For>
        </div>
      </Show>
    </CardShell>
  );
}

function QuoteChip(props: { row: TVQuoteRow }) {
  const pctNum = parseFloat(props.row.pct);
  const up = !Number.isFinite(pctNum) ? null : pctNum >= 0;
  const color = up == null ? "var(--ink-3)" : up ? "#d97757" : "#6fb98a";
  return (
    <div style={{
      display: "grid",
      "grid-template-columns": "minmax(0, 2.4fr) minmax(0, 1.2fr) minmax(0, 1fr)",
      "align-items": "baseline",
      gap: "10px",
      padding: "6px 8px",
      background: "rgba(255, 255, 255, 0.025)",
      border: "1px solid var(--line-1)",
      "border-radius": "5px",
      "font-family": "var(--font-mono)",
      "font-size": "11.5px",
    }}>
      <div style={{ overflow: "hidden", "text-overflow": "ellipsis", "white-space": "nowrap" }}>
        <span style={{ color: "var(--ink-0)", "font-weight": 600 }}>{props.row.symbol}</span>
        <Show when={props.row.name && props.row.name !== "—"}>
          <span style={{ color: "var(--ink-3)", "margin-left": "6px" }}>{props.row.name}</span>
        </Show>
      </div>
      <div style={{ color: "var(--ink-1)", "text-align": "right" }}>{props.row.close}</div>
      <div style={{ color, "text-align": "right", "font-weight": 600 }}>{props.row.pct}%</div>
    </div>
  );
}

/* ---------- tushare_quote · candlestick ---------- */

interface OhlcvRow {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  pctChg: number;
  vol: number;
}

function parseTushareTable(md: string): OhlcvRow[] {
  const rows: OhlcvRow[] = [];
  const re = /^\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([+\-\d.]+)\s*\|\s*([\d.]+)\s*\|/;
  for (const line of md.split("\n")) {
    const m = line.match(re);
    if (!m) continue;
    const [, date, o, h, l, c, p, v] = m;
    rows.push({
      date,
      open: parseFloat(o),
      high: parseFloat(h),
      low: parseFloat(l),
      close: parseFloat(c),
      pctChg: parseFloat(p),
      vol: parseFloat(v),
    });
  }
  return rows;
}

function Candlestick(props: { data: OhlcvRow[]; height: number }) {
  let host!: HTMLDivElement;
  let chart: IChartApi | null = null;
  let series: ISeriesApi<"Candlestick"> | null = null;
  let ro: ResizeObserver | null = null;

  const toSeriesData = () =>
    props.data.map((d) => ({
      time: d.date,
      open: d.open,
      high: d.high,
      low: d.low,
      close: d.close,
    }));

  onMount(() => {
    if (!host) return;
    chart = createChart(host, {
      height: props.height,
      width: host.clientWidth || 560,
      autoSize: false,
      layout: {
        background: { color: "transparent" },
        textColor: "rgba(180, 165, 150, 0.7)",
        fontSize: 10,
        fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
      },
      grid: {
        vertLines: { color: "rgba(255, 240, 220, 0.04)" },
        horzLines: { color: "rgba(255, 240, 220, 0.06)" },
      },
      timeScale: {
        timeVisible: false,
        borderColor: "rgba(255, 240, 220, 0.08)",
        fixLeftEdge: true,
        fixRightEdge: true,
      },
      rightPriceScale: {
        borderColor: "rgba(255, 240, 220, 0.08)",
      },
      crosshair: {
        vertLine: { color: "rgba(217, 119, 87, 0.45)", width: 1, style: 0 },
        horzLine: { color: "rgba(217, 119, 87, 0.45)", width: 1, style: 0 },
      },
      handleScroll: false,
      handleScale: false,
    });
    series = chart.addSeries(CandlestickSeries, {
      // Red-up / green-down — Chinese A-share convention since this card
      // is primarily for tushare CN equities.
      upColor: "#d97757",
      downColor: "#6fb98a",
      borderVisible: false,
      wickUpColor: "#d97757",
      wickDownColor: "#6fb98a",
    });
    series.setData(toSeriesData());
    chart.timeScale().fitContent();

    ro = new ResizeObserver(() => {
      if (chart && host) {
        chart.applyOptions({ width: host.clientWidth });
        chart.timeScale().fitContent();
      }
    });
    ro.observe(host);
  });

  // Push new data through whenever the rows change (e.g. tool re-runs).
  createEffect(() => {
    if (!series) return;
    series.setData(toSeriesData());
    chart?.timeScale().fitContent();
  });

  onCleanup(() => {
    ro?.disconnect();
    chart?.remove();
    chart = null;
    series = null;
  });

  return <div ref={host} style={{ width: "100%", height: `${props.height}px` }} />;
}

function TushareCard(props: { tool: ToolCallView }) {
  const args = parseArgs(props.tool);
  const tsCode = String(args.ts_code ?? "");
  const rows = createMemo(() => parseTushareTable(props.tool.output_preview ?? ""));
  const last = () => rows().length > 0 ? rows()[rows().length - 1] : null;
  const detail = () => {
    const r = last();
    if (!r) return tsCode;
    const sign = r.pctChg >= 0 ? "+" : "";
    return `${tsCode} · ${r.close.toFixed(2)} (${sign}${r.pctChg.toFixed(2)}%)`;
  };

  return (
    <CardShell
      status={props.tool.status}
      badge="market · A 股"
      detail={detail()}
      callId={props.tool.call_id}
      span={2}
    >
      <Show
        when={rows().length > 0}
        fallback={
          <div style={{ color: "var(--ink-3)", "font-size": "11.5px" }}>
            <Show when={props.tool.status === "in_progress"} fallback="No data.">
              Fetching A-share OHLCV…
            </Show>
          </div>
        }
      >
        <Candlestick data={rows()} height={180} />
      </Show>
    </CardShell>
  );
}

/* ---------- sec_filing_fetch ---------- */

interface SecFiling {
  form: string;
  filed: string;
  primary_doc_url: string;
  description?: string;
}

function SecFilingCard(props: { tool: ToolCallView }) {
  const args = parseArgs(props.tool);
  const ticker = String(args.ticker ?? "").toUpperCase();
  const preview = props.tool.output_preview ?? "";
  const parsed = safeParseJson(preview) as
    | { filings?: SecFiling[]; company_name?: string } | null;
  const filings: SecFiling[] = parsed?.filings
    ?? (extractObjectsAfter(preview, "\"filings\"") as SecFiling[]);
  return (
    <CardShell
      status={props.tool.status}
      badge="sec · edgar"
      detail={parsed?.company_name ? `${ticker} · ${parsed.company_name}` : ticker}
      callId={props.tool.call_id}
    >
      <Show
        when={filings.length > 0}
        fallback={
          <div style={{ color: "var(--ink-3)", "font-size": "11.5px" }}>
            <Show when={props.tool.status === "in_progress"} fallback="No filings.">
              Fetching filings…
            </Show>
          </div>
        }
      >
        <div style={{ display: "flex", "flex-direction": "column", gap: "6px" }}>
          <For each={filings.slice(0, 5)}>{(f) => (
            <a
              href={f.primary_doc_url}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              style={{
                display: "flex",
                gap: "10px",
                padding: "6px 10px",
                background: "rgba(255, 255, 255, 0.025)",
                border: "1px solid var(--line-1)",
                "border-radius": "6px",
                "font-family": "var(--font-mono)",
                "font-size": "11px",
                color: "var(--ink-1)",
                "text-decoration": "none",
              }}
            >
              <span style={{ "min-width": "50px", color: "var(--clay-soft)" }}>{f.form}</span>
              <span style={{ "min-width": "100px", color: "var(--ink-3)" }}>{f.filed}</span>
              <span style={{ flex: 1, "white-space": "nowrap", overflow: "hidden", "text-overflow": "ellipsis" }}>
                {f.description || f.primary_doc_url.split("/").slice(-1)[0]}
              </span>
            </a>
          )}</For>
        </div>
      </Show>
    </CardShell>
  );
}

/* ---------- generic fallback ---------- */

function GenericToolCard(props: { tool: ToolCallView }) {
  const args = parseArgs(props.tool);
  const summary = (() => {
    if (typeof args.url === "string") return String(args.url);
    if (typeof args.query === "string") return String(args.query);
    if (typeof args.ts_code === "string") return String(args.ts_code);
    if (Array.isArray(args.tickers)) return (args.tickers as string[]).join(", ");
    return JSON.stringify(args).slice(0, 60);
  })();
  return (
    <CardShell status={props.tool.status} badge={props.tool.name} detail={summary} callId={props.tool.call_id}>
      <Show when={props.tool.output_preview}>
        <div style={{
          "font-family": "var(--font-mono)",
          "font-size": "11px",
          color: "var(--ink-2)",
          "white-space": "pre-wrap",
          "max-height": "120px",
          overflow: "hidden",
        }}>{props.tool.output_preview}</div>
      </Show>
    </CardShell>
  );
}
